/*
 Background Image Carousel
 Created: Jan 17th, 2012 by DynamicDrive.com. This notice must stay intact for usage 
 Author: Dynamic Drive at http://www.dynamicdrive.com/
 Visit http://www.dynamicdrive.com/ for full source code
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,c,d){a instanceof String&&(a=String(a));for(var b=a.length,e=0;e<b;e++){var g=a[e];if(c.call(d,g,e,a))return{i:e,v:g}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,d){a!=Array.prototype&&a!=Object.prototype&&(a[c]=d.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,c,d,b){if(c){d=$jscomp.global;a=a.split(".");for(b=0;b<a.length-1;b++){var e=a[b];e in d||(d[e]={});d=d[e]}a=a[a.length-1];b=d[a];c=c(b);c!=b&&null!=c&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:c})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,d){return $jscomp.findInternal(this,a,d).v}},"es6","es3");jQuery.noConflict();
function bgCarousel(a){var c=jQuery;this.setting={displaymode:{type:"auto",pause:2E3,stoponclick:!1,cycles:2,pauseonmouseover:!0},activeslideclass:"selectedslide",orientation:"h",persist:!0,slideduration:500};jQuery.extend(this.setting,a);this.setting.displaymode.pause+=400+this.setting.slideduration;a=this.setting.persist?bgCarousel.routines.getCookie("slider-"+this.setting.wrapperid):0;this.curslide=null==a||a>this.setting.imagearray.length-1?0:parseInt(a);this.curstep=0;this.animation_isrunning=
!1;this.posprop="h"==this.setting.orientation?"left":"top";a=null;var d=this,b=this.setting;a=[];for(var e=0,g="",f=0,h=b.imagearray.length;f<h;f++)a[f]=new Image,c(a[f]).bind("load error",function(){e++;e==h&&c(function(){d.init(c,g)})}),a[f].src=b.imagearray[f][0],g+=bgCarousel.routines.getSlideHTML(b,b.imagearray[f],"100%","100%",this.posprop)+"\n";c(window).bind("unload",function(){d.setting.persist&&bgCarousel.routines.setCookie("slider-"+b.wrapperid,d.curslide)})}
bgCarousel.prototype={slide:function(a,c){if(this.curslide!=a){var d=this,b=this.setting,e=bgCarousel.routines.createobj;c=b.dimensions["right"==c||"left"==c?0:1]*("right"==c||"down"==c?-1:1);var g=-c,f=this.posprop;null!=this.animation_isrunning&&(this.animation_isrunning=!0);this.$imageslides.eq(a).show().css(e([f,c],["opacity",.5])).stop().animate(e([f,0]),b.slideduration,function(){jQuery(this).addClass(b.activeslideclass).animate({opacity:1}).find("div.desc").stop().slideDown();d.animation_isrunning=
!1}).find("div.desc").hide();this.$imageslides.eq(this.curslide).removeClass(b.activeslideclass).stop().animate(e([f,g]),b.slideduration,function(){jQuery(this).hide()});this.curslide=a}},navigate:function(a){var c=this,d=this.setting;clearTimeout(this.rotatetimer);d.displaymode.stoponclick||"manual"==d.displaymode.type||(this.curstep="back"==a?this.curstep-1:this.curstep+1,this.rotatetimer=setTimeout(function(){c.rotate()},d.displaymode.pause));d="back"==a?"h"==d.orientation?"right":"down":"h"==
d.orientation?"left":"up";a="back"==a?this.curslide-1:this.curslide+1;a=0>a?this.$imageslides.length-1:a>this.$imageslides.length-1?0:a;0==this.animation_isrunning&&this.slide(a,d)},rotate:function(){var a=this,c=this.setting;if(this.ismouseover)this.rotatetimer=setTimeout(function(){a.rotate()},c.displaymode.pause);else if(this.slide(this.curslide<this.$imageslides.length-1?this.curslide+1:0,this.posprop),0==c.displaymode.cycles||this.curstep<this.maxsteps-1)this.rotatetimer=setTimeout(function(){a.rotate()},
c.displaymode.pause),this.curstep++},init:function(a,c){var d=this,b=this.setting;this.$wrapperdiv=a("#"+b.wrapperid);b.dimensions=[this.$wrapperdiv.width(),this.$wrapperdiv.height()];this.$wrapperdiv.css({position:"relative",visibility:"visible",overflow:"hidden",backgroundImage:"none",width:b.dimensions[0],height:b.dimensions[1]});0==this.$wrapperdiv.length?alert('Error: DIV with ID "'+b.wrapperid+'" not found on page.'):(this.$wrapperdiv.html(c),this.$imageslides=this.$wrapperdiv.find("div.background").hide(),
this.$imageslides.eq(this.curslide).show().css(bgCarousel.routines.createobj(["opacity",.5],[this.posprop,0])).addClass(b.activeslideclass).stop().animate({opacity:1}).find("div.desc").slideDown(),"h"==b.orientation?b.navbuttons.slice(0,2):b.navbuttons.slice(2),a("").click(function(){var a=this.getAttribute("data-dir");b.curslide="right"==a?b.curslide==b.content.length-1?0:b.curslide+1:0==b.curslide?b.content.length-1:b.curslide-1;d.navigate(a)}).appendTo(this.$wrapperdiv),"auto"==b.displaymode.type&&
(b.displaymode.pause+=b.slideduration,this.maxsteps=b.displaymode.cycles*this.$imageslides.length,b.displaymode.pauseonmouseover&&(this.$wrapperdiv.mouseenter(function(){d.ismouseover=!0}),this.$wrapperdiv.mouseleave(function(){d.ismouseover=!1})),this.rotatetimer=setTimeout(function(){d.rotate()},b.displaymode.pause)))}};
bgCarousel.routines={getSlideHTML:function(a,c,d,b,e){return'<div class="background" style="background-image:url('+c[0]+");"+(e+":"+("left"==e?d:b))+'">'+(c[1]?'<div class="desc" style="display:none">'+c[1]+"</div>\n":"")+"</div>"},getCookie:function(a){a=new RegExp(a+"=[^;]+","i");return document.cookie.match(a)?document.cookie.match(a)[0].split("=")[1]:null},setCookie:function(a,c){document.cookie=a+"="+c+";path=/"},createobj:function(){for(var a={},c=0;c<arguments.length;c++)a[arguments[c][0]]=
arguments[c][1];return a}}; //# sourceMappingURL=/en/t4-media/one-web/university/admin-assets/js/map/bgcarousel-min.js.map
