var $jscomp$templatelit$2=["/cookies"];$jscomp$templatelit$2.raw=["/cookies"];var $jscomp$templatelit$1=["https://"];$jscomp$templatelit$1.raw=["https://"];var $jscomp$templatelit$0=["https://www.uhi.ac.uk/en/cookies"];$jscomp$templatelit$0.raw=["https://www.uhi.ac.uk/en/cookies"];var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};
$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");$jscomp.polyfill("Object.is",function(a){return a?a:function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,c){var b=this;b instanceof String&&(b=String(b));var e=b.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=b[c];if(f===a||Object.is(f,a))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,c){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,c||0)}},"es6","es3");
$.urlParam=function(a){a=(new RegExp("[?&]"+a+"=([^&#]*)")).exec(window.location.href);return null==a?null:decodeURI(a[1])||0};function noTab(){var a=$("#modalAlert").find("select, input, textarea, button, a").filter(":visible"),b=a.first(),c=a.last();b.focus();c.on("keydown",function(a){9!==a.which||a.shiftKey||(a.preventDefault(),b.focus())});b.on("keydown",function(a){9===a.which&&a.shiftKey&&(a.preventDefault(),c.focus())})}
function setCharAt(a,b,c){b=Number(b);if(b>a.length-1)return a;a.substring(b);return a.substring(0,b)+c+a.substring(b+1)}function getPrefsUrl(){return-1!==document.URL.indexOf("/en/")?"https://"+window.location.hostname+"/en/cookies":"https://"+window.location.hostname+"/cookies"}function getPrefsUrlOnClick(){return-1!==document.URL.indexOf("/en/")?String.raw($jscomp$templatelit$0):String.raw($jscomp$templatelit$1)+window.location.hostname+String.raw($jscomp$templatelit$2)}
function getNoMediaText(){return"<p style='background-color:#666666;color:#ffffff;height:100%;display:inline-block;'>We have removed this content.<br/> Please <a href='"+getPrefsUrl()+"' style='color:white;text-decoration: underline;'>change your cookie preferences</a> to see this content.</p>"}function allowPerfCookies(){var a=getCookie("_uhic");return""==a?!1:"1"==a.charAt(2)?!0:!1}function allowFunctCookies(){var a=getCookie("_uhic");return""==a?!0:"1"==a.charAt(1)?!0:!1}
function allowThirdCookies(){var a=getCookie("_uhic");return""==a?!0:"1"==a.charAt(3)?!0:!1}function allowTargetingCookies(){var a=document.URL,b=getCookie("_uhic");return""==b||-1!==a.indexOf("/cookies")?!1:"1"==b.charAt(4)?!0:!1}
function setCookie(a,b,c){var d=new Date;d.setTime(d.getTime()+864E5*c);c="expires="+d.toUTCString();-1<window.location.href.indexOf("uhisf")?document.cookie=a+"="+b+"; Domain=.uhisf.com; secure=true; samesite=strict; "+c+";path=/":document.cookie=a+"="+b+"; Domain=.uhi.ac.uk; secure=true; samesite=strict; "+c+";path=/"}
function getCookie(a){a+="=";for(var b=decodeURIComponent(document.cookie).split(";"),c=0;c<b.length;c++){for(var d=b[c];" "==d.charAt(0);)d=d.substring(1);if(0==d.indexOf(a))return d.substring(a.length,d.length)}return""}
function warningCookieRead(){var a=getCookie("_uhic");dataLayer.push({allowPerfCookies:allowPerfCookies()});dataLayer.push({allowTargetingCookies:allowTargetingCookies()});switch(a){case "":removeSocialMedia();setCookie("_uhic","91000",90);showCookieMessage();break;case "91000":removeSocialMedia();showCookieMessage();break;case "0111":showCookieMessage();break;case "1111":showCookieMessage();break;default:setCookie("_uhic",a,90),allowThirdCookies()||removeSocialMedia()}}
function firstView(){var a=!1;$(window).scroll(function(){a||runGA();a=!0})}function runGA(){(function(a,b,c,d,e,f,g){a.GoogleAnalyticsObject=e;a[e]=a[e]||function(){(a[e].q=a[e].q||[]).push(arguments)};a[e].l=1*new Date;f=b.createElement(c);g=b.getElementsByTagName(c)[0];f.async=1;f.src=d;g.parentNode.insertBefore(f,g)})(window,document,"script","//www.google-analytics.com/analytics.js","ga");ga("create","UA-24468473-1","uhi.ac.uk");ga("send","pageview")}
function showCookieMessage(){if(-1==window.location.pathname.indexOf("/cookies/")){var a='<div id="uhi-cookie-alert" class="cookie-notice-2"><div class="flex-container"><div class="cookie-message"><p>We use cookies you accept along with necessary cookies to help us run this website and to promote the university using social media and other online tools. If you\u2019re happy with this, click Accept all. If you would like to know more, click on Settings. You are free to amend your settings at any time from our cookies page.</p></div><div class="cookie-buttons"><button class="cookie-accept" onclick="warningCookieContinue();">Accept all</button>'+
('<button class="cookie-settings" onclick="location.href=`'+getPrefsUrl()+'`;">Settings</button>');a+="</div></div></div>";$(".message").css("display","none");$("body").prepend(a)}}function removeSocialMedia(){removeIframes();removeFacebook();removeTwitter();removeBBox();removeEmbeddedFeeds()}function removeIframes(){for(var a=document.getElementsByTagName("iframe"),b=a.length-1;0<=b;b--)a[b].src.includes("recaptcha")||(a[b].outerHTML=getNoMediaText())}
function disableIframes(){for(var a=document.getElementsByTagName("iframe"),b=a.length-1;0<=b;b--)a[b].src="xx"+a[b].src}function removeFacebook(){for(var a=document.getElementsByClassName("fb-page"),b=a.length-1;0<=b;b--)$(a[b]).prevAll()[0].outerHTML="",a[b].outerHTML=getNoMediaText()}function removeTwitter(){for(var a=document.getElementsByClassName("twitter-timeline"),b=a.length-1;0<=b;b--)$(a[b]).nextAll()[0].outerHTML="",a[b].outerHTML=getNoMediaText()}
function removeBBox(){var a=document.getElementById("bbox-root-a00158dc-ea3d-4015-80aa-58043f92bc9a");a&&($(a).nextAll()[0].outerHTML="",a.outerHTML=getNoMediaText())}function removeEmbeddedFeeds(){var a=document.getElementById("embedded-feed");if(a){var b=$(a).nextAll()[0],c=$(a).nextAll()[1];b.outerHTML="";c.outerHTML="";a.outerHTML=getNoMediaText()}}
function warningCookieContinue(){getCookie("_uhic");setCookie("_uhic","11111",90);var a=document.getElementById("uhi-cookie-alert");a&&a.parentNode.removeChild(a);document.getElementsByClassName("message")[0]&&$(".message").css("display","block")}
function cookieConfigInit(){var a=getCookie("_uhic");if(""==a||"0000"==a||"0111"==a||"1111"==a||"91111"==a||"91000"==a)setCookie("_uhic","10000",90),a="10000";"0"==a.charAt(1)&&$("#cFunct").prop("checked",!1);"0"==a.charAt(2)&&$("#cPerf").prop("checked",!1);"0"==a.charAt(3)&&$("#cThird").prop("checked",!1);"0"==a.charAt(4)&&$("#cTarget").prop("checked",!1);"11111"==a?$("#cAll").prop("checked",!0):$("#cAll").prop("checked",!1)}
function cookieConfigChange(a){cVal=a.checked?"1":"0";if(0==a.value)$("#cFunct").prop("checked",a.checked),$("#cPerf").prop("checked",a.checked),$("#cThird").prop("checked",a.checked),$("#cTarget").prop("checked",a.checked),cVal=a.checked?setCookie("_uhic","11111",90):setCookie("_uhic","10000",90);else{0==cVal&&$("#cAll").prop("checked",!1);var b=getCookie("_uhic");b=setCharAt(b,a.value,cVal);console.log(a.value+": "+a.checked+": "+b);setCookie("_uhic",b,90);"11111"==b?$("#cAll").prop("checked",!0):
$("#cAll").prop("checked",!1);2!=a.value||a.checked||(document.cookie="_ga=; Path=/; Domain=.uhi.ac.uk; Expires=Thu, 01 Jan 1970 00:00:01 GMT;",document.cookie="_gat=; Path=/; Domain=.uhi.ac.uk; Expires=Thu, 01 Jan 1970 00:00:01 GMT;",document.cookie="_gid=; Path=/; Domain=.uhi.ac.uk; Expires=Thu, 01 Jan 1970 00:00:01 GMT;");1!=a.value||a.checked||(document.cookie="slider-bigBG=; Path=/; Expires=Thu, 01 Jan 1970 00:00:01 GMT;",document.cookie="slider-smallBG=; Path=/; Expires=Thu, 01 Jan 1970 00:00:01 GMT;")}}
function campaignCookieRead(){""==getCookie('_<t4 type="navigation" name="Config Funnelback Scope getter" id="448" />_campaign')&&showCampaignMessage('<t4 type="navigation" name="Site Wide Campaign Banner getter" id="449" />')}function showCampaignMessage(a){0<=$(location).attr("href").indexOf("/gd/")&&(a=a.replace(/en.gif/g,"gd.gif"));$("body").prepend(a)}
function campaignMessageClose(){setCookie('_<t4 type="navigation" name="Config Funnelback Scope getter" id="448" />_campaign',"1",1);$(".campaign-banner").remove()}; //# sourceMappingURL=/en/t4-media/one-web/university/admin-assets/js/map/cookie-min.js.map
