function setCharAt(a,b,c){b=Number(b);if(b>a.length-1)return a;a.substring(b);return a.substring(0,b)+c+a.substring(b+1)}function getPrefsUrl(){return-1!==document.URL.indexOf("/en/")?"https://www.uhi.ac.uk/en/cookies":"https://"+window.location.hostname+"/cookies"}
function getNoMediaText(){return"<p style='background-color:#808080;color:#ffffff;height:100%;display:inline-block;'>We have removed this content.<br/> Please <a href='"+getPrefsUrl()+"'>change your cookie preferences</a> to see our social media.</p>"}function allowPerfCookies(){var a=getCookie("_uhic");return""==a?!1:"1"==a.charAt(2)?!0:!1}function allowFunctCookies(){var a=getCookie("_uhic");return""==a?!0:"1"==a.charAt(1)?!0:!1}
function allowThirdCookies(){var a=getCookie("_uhic");return""==a?!0:"1"==a.charAt(3)?!0:!1}function setCookie(a,b,c){var d=new Date;d.setTime(d.getTime()+864E5*c);c="expires="+d.toUTCString();-1<window.location.href.indexOf("uhisf")?(console.log("uhisf cookie"),document.cookie=a+"="+b+"; Domain=.uhisf.com; "+c+";path=/"):document.cookie=a+"="+b+"; Domain=.uhi.ac.uk; "+c+";path=/"}
function getCookie(a){a+="=";for(var b=decodeURIComponent(document.cookie).split(";"),c=0;c<b.length;c++){for(var d=b[c];" "==d.charAt(0);)d=d.substring(1);if(0==d.indexOf(a))return d.substring(a.length,d.length)}return""}
function warningCookieRead(){var a=getCookie("_uhic");switch(a){case "":removeSocialMedia();firstView();setCookie("_uhic","9111",90);showCookieMessage();break;case "9111":setCookie("_uhic","0111",90);showCookieMessage();break;case "0111":showCookieMessage();break;default:setCookie("_uhic",a,90),allowThirdCookies()||removeSocialMedia()}}function firstView(){var a=!1;$(window).scroll(function(){a||runGA();a=!0})}
function runGA(){(function(a,b,c,d,e,f,g){a.GoogleAnalyticsObject=e;a[e]=a[e]||function(){(a[e].q=a[e].q||[]).push(arguments)};a[e].l=1*new Date;f=b.createElement(c);g=b.getElementsByTagName(c)[0];f.async=1;f.src=d;g.parentNode.insertBefore(f,g)})(window,document,"script","//www.google-analytics.com/analytics.js","ga");ga("create","UA-24468473-1","uhi.ac.uk");ga("send","pageview")}
function showCookieMessage(){if(-1==window.location.pathname.indexOf("/cookies/")){var a='<div id="uhi-cookie-alert" class="navigation--home-message message--cookie"><p><a class="close" title="Close" href="#" onclick="warningCookieContinue();">~</a></p>'+('<p>We use <a href="'+getPrefsUrl()+'">cookies</a> to provide the best experience when browsing our site. These can be for perfomance or functional reasons.  ');a=a+'Some pages may also contain "third party" cookies from social media sites where we have used embedded content.  '+
('You can <a href="'+getPrefsUrl()+'">change your cookie settings for our site</a>, or if you choose you can continue and  ');a+='we will assume that you are happy to receive all cookies from our site.</p><div id="cookies-continue" onclick="warningCookieContinue();">Continue</div></div>';$(".navigation--home-message").css("display","none");$("body").prepend(a)}}function removeSocialMedia(){removeIframes();removeFacebook();removeTwitter();removeBBox();removeEmbeddedFeeds()}
function removeIframes(){for(var a=document.getElementsByTagName("iframe"),b=a.length-1;0<=b;b--)a[b].outerHTML=getNoMediaText()}function disableIframes(){for(var a=document.getElementsByTagName("iframe"),b=a.length-1;0<=b;b--)a[b].src="xx"+a[b].src}function removeFacebook(){for(var a=document.getElementsByClassName("fb-page"),b=a.length-1;0<=b;b--)$(a[b]).prevAll()[0].outerHTML="",a[b].outerHTML=getNoMediaText()}
function removeTwitter(){for(var a=document.getElementsByClassName("twitter-timeline"),b=a.length-1;0<=b;b--)$(a[b]).nextAll()[0].outerHTML="",a[b].outerHTML=getNoMediaText()}function removeBBox(){var a=document.getElementById("bbox-root-a00158dc-ea3d-4015-80aa-58043f92bc9a");a&&($(a).nextAll()[0].outerHTML="",a.outerHTML=getNoMediaText())}
function removeEmbeddedFeeds(){var a=document.getElementById("embedded-feed");if(a){var b=$(a).nextAll()[0],c=$(a).nextAll()[1];b.outerHTML="";c.outerHTML="";a.outerHTML=getNoMediaText()}}function warningCookieContinue(){"9111"==getCookie("_uhic")&&runGA();setCookie("_uhic","1111",90);var a=document.getElementById("uhi-cookie-alert");a.parentNode.removeChild(a);document.getElementsByClassName("navigation--home-message")[0]&&$(".navigation--home-message").css("display","block")}
function cookieConfigInit(){var a=getCookie("_uhic");""==a||"0000"==a||"0111"==a?(setCookie("_uhic","1111",90),$("#cFunct").prop("checked",!0),$("#cPerf").prop("checked",!0),$("#cThird").prop("checked",!0)):("1"==a.charAt(1)&&$("#cFunct").prop("checked",!0),"1"==a.charAt(2)&&$("#cPerf").prop("checked",!0),"1"==a.charAt(3)&&$("#cThird").prop("checked",!0))}
function cookieConfigChange(a){cVal=a.checked?"1":"0";var b=getCookie("_uhic");b=setCharAt(b,a.value,cVal);setCookie("_uhic",b,90);2!=a.value||a.checked||(document.cookie="_ga=; Path=/; Domain=.uhi.ac.uk; Expires=Thu, 01 Jan 1970 00:00:01 GMT;",document.cookie="_gat=; Path=/; Domain=.uhi.ac.uk; Expires=Thu, 01 Jan 1970 00:00:01 GMT;",document.cookie="_gid=; Path=/; Domain=.uhi.ac.uk; Expires=Thu, 01 Jan 1970 00:00:01 GMT;");1!=a.value||a.checked||(document.cookie="slider-bigBG=; Path=/; Expires=Thu, 01 Jan 1970 00:00:01 GMT;",
document.cookie="slider-smallBG=; Path=/; Expires=Thu, 01 Jan 1970 00:00:01 GMT;")}; //# sourceMappingURL=/en/t4-media/one-web/university/admin-assets/js/map/cookie-min.js.map
