/*
 FitVids 1.0

 Copyright 2011, Chris Coyier - http://css-tricks.com + Dave Rupert - http://daverupert.com
 Credit to Thierry Koblentz - http://www.alistapart.com/articles/creating-intrinsic-ratios-for-video/
 Released under the WTFPL license - http://sam.zoy.org/wtfpl/

 Date: Thu Sept 01 18:00:00 2011 -0500
 hoverIntent r7 // 2013.03.11 // jQuery 1.9.1+
 http://cherne.net/brian/resources/jquery.hoverIntent.html

 You may use hoverIntent under the terms of the MIT license. Basically that
 means you are free to use hoverIntent as long as this header is left intact.
 Copyright 2007, 2013 Brian Cherne
 Copyright (c) 2007-2015 Ariel Flesler - aflesler<a>gmail<d>com | http://flesler.blogspot.com
 Licensed under MIT
 @author Ariel Flesler
 @version 2.1.2
 Plugin: jQuery Parallax
Version 1.1
Author: Ian Lunn
Author URL: http://www.ianlunn.co.uk/
Plugin URL: http://www.ianlunn.co.uk/plugins/jquery-parallax/

Dual licensed under the MIT and GPL licenses:
http://www.opensource.org/licenses/mit-license.php
http://www.gnu.org/licenses/gpl.html
 scrollorama - The jQuery plugin for doing cool scrolly stuff
 by John Polacek (@johnpolacek)

 Dual licensed under MIT and GPL.
 jQuery Easing v1.3 - http://gsgd.co.uk/sandbox/jquery/easing/

 Uses the built in easing capabilities added In jQuery 1.1
 to offer multiple easing options

 TERMS OF USE - jQuery Easing

 Open source under the BSD License. 

 Copyright ? 2008 George McGinley Smith
 All rights reserved.

 Background Image Carousel
 Created: Jan 17th, 2012 by DynamicDrive.com. This notice must stay intact for usage 
 Author: Dynamic Drive at http://www.dynamicdrive.com/
 Visit http://www.dynamicdrive.com/ for full source code
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(d,b,a){d instanceof String&&(d=String(d));for(var c=d.length,e=0;e<c;e++){var f=d[e];if(b.call(a,f,e,d))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,b,a){d!=Array.prototype&&d!=Object.prototype&&(d[b]=a.value)};
$jscomp.getGlobal=function(d){return"undefined"!=typeof window&&window===d?d:"undefined"!=typeof global&&null!=global?global:d};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(d,b,a,c){if(b){a=$jscomp.global;d=d.split(".");for(c=0;c<d.length-1;c++){var e=d[c];e in a||(a[e]={});a=a[e]}d=d[d.length-1];c=a[d];b=b(c);b!=c&&null!=b&&$jscomp.defineProperty(a,d,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.prototype.find",function(d){return d?d:function(b,a){return $jscomp.findInternal(this,b,a).v}},"es6","es3");var $=jQuery;(function(){for(var d,b=function(){},a="assert clear count debug dir dirxml error exception group groupCollapsed groupEnd info log markTimeline profile profileEnd table time timeEnd timeStamp trace warn".split(" "),c=a.length,e=window.console=window.console||{};c--;)d=a[c],e[d]||(e[d]=b)})();
(function(d){d={init:function(){this.browser=this.searchString(this.dataBrowser)||"An unknown browser";this.version=this.searchVersion(navigator.userAgent)||this.searchVersion(navigator.appVersion)||"an unknown version";this.OS=this.searchString(this.dataOS)||"an unknown OS"},searchString:function(b){for(var a=0;a<b.length;a++){var c=b[a].string,e=b[a].prop;this.versionSearchString=b[a].versionSearch||b[a].identity;if(c){if(-1!=c.indexOf(b[a].subString))return b[a].identity}else if(e)return b[a].identity}},
searchVersion:function(b){var a=b.indexOf(this.versionSearchString);if(-1!=a)return parseFloat(b.substring(a+this.versionSearchString.length+1))},dataBrowser:[{string:navigator.userAgent,subString:"Chrome",identity:"Chrome"},{string:navigator.userAgent,subString:"OmniWeb",versionSearch:"OmniWeb/",identity:"OmniWeb"},{string:navigator.vendor,subString:"Apple",identity:"Safari",versionSearch:"Version"},{prop:window.opera,identity:"Opera"},{string:navigator.vendor,subString:"iCab",identity:"iCab"},{string:navigator.vendor,
subString:"KDE",identity:"Konqueror"},{string:navigator.userAgent,subString:"Firefox",identity:"Firefox"},{string:navigator.vendor,subString:"Camino",identity:"Camino"},{string:navigator.userAgent,subString:"Netscape",identity:"Netscape"},{string:navigator.userAgent,subString:"MSIE",identity:"Explorer",versionSearch:"MSIE"},{string:navigator.userAgent,subString:"Gecko",identity:"Mozilla",versionSearch:"rv"},{string:navigator.userAgent,subString:"Mozilla",identity:"Netscape",versionSearch:"Mozilla"}],
dataOS:[{string:navigator.platform,subString:"Win",identity:"Windows"},{string:navigator.platform,subString:"Mac",identity:"Mac"},{string:navigator.userAgent,subString:"iPhone",identity:"iPhone/iPod"},{string:navigator.platform,subString:"Linux",identity:"Linux"}]};d.init();window.$.client={os:d.OS,browser:d.browser}})(jQuery);
(function(d){d.fn.fitVids=function(b){var a={customSelector:null};if(!document.getElementById("fit-vids-style")){var c=document.createElement("div"),e=document.getElementsByTagName("base")[0]||document.getElementsByTagName("script")[0];c.className="fit-vids-style";c.id="fit-vids-style";c.style.display="none";c.innerHTML="&shy;<style> .fluid-width-video-wrapper { width: 100%; position: relative; padding: 0; } .fluid-width-video-wrapper iframe, .fluid-width-video-wrapper object, .fluid-width-video-wrapper embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; } </style>";
e.parentNode.insertBefore(c,e)}b&&d.extend(a,b);return this.each(function(){var b="iframe[src*='player.vimeo.com'] iframe[src*='youtube.com'] iframe[src*='youtube-nocookie.com'] iframe[src*='kickstarter.com'][src*='video.html'] object embed".split(" ");a.customSelector&&b.push(a.customSelector);b=d(this).find(b.join(","));b=b.not("object object");b.each(function(){var a=d(this);if(!("embed"===this.tagName.toLowerCase()&&a.parent("object").length||a.parent(".fluid-width-video-wrapper").length)){var b=
"object"===this.tagName.toLowerCase()||a.attr("height")&&!isNaN(parseInt(a.attr("height"),10))?parseInt(a.attr("height"),10):a.height(),e=isNaN(parseInt(a.attr("width"),10))?a.width():parseInt(a.attr("width"),10);b/=e;a.attr("id")||a.attr("id","fitvid"+Math.floor(999999*Math.random()));a.wrap('<div class="fluid-width-video-wrapper"></div>').parent(".fluid-width-video-wrapper").css("padding-top",100*b+"%");a.removeAttr("height").removeAttr("width")}})})}})(jQuery);
(function(d){d.fn.hoverIntent=function(b,a,c){var e={interval:100,sensitivity:7,timeout:0};e="object"===typeof b?d.extend(e,b):d.isFunction(a)?d.extend(e,{over:b,out:a,selector:c}):d.extend(e,{over:b,out:b,selector:a});var f,g,k,m,q=function(a){f=a.pageX;g=a.pageY},r=function(a,b){b.hoverIntent_t=clearTimeout(b.hoverIntent_t);if(Math.abs(k-f)+Math.abs(m-g)<e.sensitivity)return d(b).off("mousemove.hoverIntent",q),b.hoverIntent_s=1,e.over.apply(b,[a]);k=f;m=g;b.hoverIntent_t=setTimeout(function(){r(a,
b)},e.interval)};b=function(a){var b=jQuery.extend({},a),c=this;c.hoverIntent_t&&(c.hoverIntent_t=clearTimeout(c.hoverIntent_t));"mouseenter"==a.type?(k=b.pageX,m=b.pageY,d(c).on("mousemove.hoverIntent",q),1!=c.hoverIntent_s&&(c.hoverIntent_t=setTimeout(function(){r(b,c)},e.interval))):(d(c).off("mousemove.hoverIntent",q),1==c.hoverIntent_s&&(c.hoverIntent_t=setTimeout(function(){c.hoverIntent_t=clearTimeout(c.hoverIntent_t);c.hoverIntent_s=0;e.out.apply(c,[b])},e.timeout)))};return this.on({"mouseenter.hoverIntent":b,
"mouseleave.hoverIntent":b},e.selector)}})(jQuery);
(function(d){"function"===typeof define&&define.amd?define(["jquery"],d):"undefined"!==typeof module&&module.exports?module.exports=d(require("jquery")):d(jQuery)})(function(d){function b(a){return!a.nodeName||-1!==d.inArray(a.nodeName.toLowerCase(),["iframe","#document","html","body"])}function a(a){return d.isFunction(a)||d.isPlainObject(a)?a:{top:a,left:a}}var c=d.scrollTo=function(a,b,c){return d(window).scrollTo(a,b,c)};c.defaults={axis:"xy",duration:0,limit:!0};d.fn.scrollTo=function(e,f,g){"object"===
typeof f&&(g=f,f=0);"function"===typeof g&&(g={onAfter:g});"max"===e&&(e=9E9);g=d.extend({},c.defaults,g);f=f||g.duration;var k=g.queue&&1<g.axis.length;k&&(f/=2);g.offset=a(g.offset);g.over=a(g.over);return this.each(function(){function m(a){var b=d.extend({},g,{queue:!0,duration:f,complete:a&&function(){a.call(r,n,g)}});t.animate(p,b)}if(null!==e){var q=b(this),r=q?this.contentWindow||window:this,t=d(r),n=e,p={};switch(typeof n){case "number":case "string":if(/^([+-]=?)?\d+(\.\d+)?(px|%)?$/.test(n)){n=
a(n);break}n=q?d(n):d(n,r);case "object":if(0===n.length)return;if(n.is||n.style)var u=(n=d(n)).offset()}var v=d.isFunction(g.offset)&&g.offset(r,n)||g.offset;d.each(g.axis.split(""),function(a,b){var e="x"===b?"Left":"Top",d=e.toLowerCase(),f="scroll"+e,h=t[f](),l=c.max(r,b);u?(p[f]=u[d]+(q?0:h-t.offset()[d]),g.margin&&(p[f]-=parseInt(n.css("margin"+e),10)||0,p[f]-=parseInt(n.css("border"+e+"Width"),10)||0),p[f]+=v[d]||0,g.over[d]&&(p[f]+=n["x"===b?"width":"height"]()*g.over[d])):(e=n[d],p[f]=e.slice&&
"%"===e.slice(-1)?parseFloat(e)/100*l:e);g.limit&&/^\d+$/.test(p[f])&&(p[f]=0>=p[f]?0:Math.min(p[f],l));!a&&1<g.axis.length&&(h===p[f]?p={}:k&&(m(g.onAfterFirst),p={}))});m(g.onAfter)}})};c.max=function(a,c){c="x"===c?"Width":"Height";var e="scroll"+c;if(!b(a))return a[e]-d(a)[c.toLowerCase()]();c="client"+c;a=a.ownerDocument||a.document;var f=a.documentElement;a=a.body;return Math.max(f[e],a[e])-Math.min(f[c],a[c])};d.Tween.propHooks.scrollLeft=d.Tween.propHooks.scrollTop={get:function(a){return d(a.elem)[a.prop]()},
set:function(a){var b=this.get(a);if(a.options.interrupt&&a._last&&a._last!==b)return d(a.elem).stop();var c=Math.round(a.now);b!==c&&(d(a.elem)[a.prop](c),a._last=this.get(a))}};return c});function RepositionNav(){var d=$(window).height(),b=$("#nav").height()/2;d=d/2-b;$("#nav").css({top:d})}
(function(d){d.fn.parallax=function(b,a,c,e){function f(a,b){b.each(function(){var b=d(this),c=b.offset().top;b=1==e?b.outerHeight(!0):b.height();c+b>=a&&c+b-m<a&&g(a,b);c<=a&&c+b>=a&&c-m<a&&c+b-m>a&&g(a,b);c+b>a&&c-m<a&&c>a&&g(a,b)})}function g(e,d){q.css({backgroundPosition:b+" "+Math.round(-(d+e-a)*c)+"px"})}var k=d(window),m=d(window).height();k.scrollTop();var q=d(this);null==b&&(b="50%");null==a&&(a=0);null==c&&(c=.1);null==e&&(e=!0);height=q.height();q.css({backgroundPosition:b+" "+Math.round(NaN*
-(e+a-c))+"px"});k.bind("scroll",function(){var a=k.scrollTop();f(a,q);d("#pixels").html(a)})}})(jQuery);
(function(d){d.scrollorama=function(b){function a(){c()}function c(){r||t(function(){e();r=!1});r=!0}function e(){var a=d(window).scrollTop();var b=0;var c;for(c=0;c<k.length;c++)k[c].top<=a-g.settings.offset&&(b=c);var e;for(c=0;c<k.length;c++)if(k[c].animations.length)for(e=0;e<k[c].animations.length;e++){var l=k[c].animations[e];c>b?(b!==c-1&&"bottom"!==l.baseline&&f(l.element,l.property,l.startVal),k[c].pin&&k[c].block.css("position","absolute").css("top",k[c].top)):c<b&&(f(l.element,l.property,
l.endVal),k[c].pin&&k[c].block.css("position","absolute").css("top",k[c].top+k[c].pin));if(c===b||b===c-1&&"bottom"===l.baseline){k[c].pin&&b===c&&k[c].block.css("position","fixed").css("top",0);var h=k[c].top+l.delay;"bottom"===l.baseline&&(h-=d(window).height());var m=h+l.duration;a<h?f(l.element,l.property,l.startVal):a>m?(f(l.element,l.property,l.endVal),k[c].pin&&k[c].block.css("position","absolute").css("top",k[c].top+k[c].pin)):(h=(a-h)/l.duration,l.easing&&d.isFunction(d.easing[l.easing])&&
(h=d.easing[l.easing](h,1E3*h,0,1,1E3)),h=l.startVal+h*(l.endVal-l.startVal),f(l.element,l.property,h))}}g.blockIndex!==b&&(g.blockIndex=b,q())}function f(a,b,c){if("rotate"===b||"zoom"===b||"scale"===b)if("rotate"===b)a.css(m+"transform","rotate("+c+"deg)");else{if("zoom"===b||"scale"===b)b="scale("+c+")","-ms-"!==m?a.css(m+"transform",b):a.css("zoom",b)}else if("background-position-x"===b||"background-position-y"===b){var e=a.css("background-position").split(" ");"background-position-x"===b&&a.css("background-position",
c+"px "+e[1]);"background-position-y"===b&&a.css("background-position",e[0]+" "+c+"px")}else"text-shadow"===b?a.css(b,"0px 0px "+c+"px #ffffff"):a.css(b,c)}var g=this,k=[],m="",q=function(){},r=!1,t=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)};g.settings=d.extend({},{offset:0,enablePin:!0},b);g.blockIndex=0;void 0===b.blocks&&alert("ERROR: Must assign blocks class selector to scrollorama plugin");
g.animate=function(a){var b,c;"string"===typeof a&&(a=d(a));for(b=0;b<k.length;b++)if(k[b].block.has(a).length){var f=k[b];var g=b}for(b=1;b<arguments.length;b++){var h=arguments[b];if("top"===h.property||"left"===h.property||"bottom"===h.property||"right"===h.property)"static"===a.css("position")&&a.css("position","relative"),cssValue=parseInt(a.css(h.property),10),void 0===h.start?h.start=isNaN(cssValue)?0:cssValue:void 0===h.end&&(h.end=isNaN(cssValue)?0:cssValue);"rotate"===h.property?(void 0===
h.start&&(h.start=0),void 0===h.end&&(h.end=0)):"zoom"===h.property||"scale"===h.property?(void 0===h.start&&(h.start=1),void 0===h.end&&(h.end=1)):"letter-spacing"===h.property&&a.css(h.property)&&(void 0===h.start&&(h.start=1),void 0===h.end&&(h.end=1));void 0===h.baseline&&(h.baseline=h.pin||f.pin||0===g?"top":"bottom");void 0===h.delay&&(h.delay=0);f.animations.push({element:a,delay:h.delay,duration:h.duration,property:h.property,startVal:void 0!==h.start?h.start:parseInt(a.css(h.property),10),
endVal:void 0!==h.end?h.end:parseInt(a.css(h.property),10),baseline:void 0!==h.baseline?h.baseline:"bottom",easing:h.easing});if(h.pin&&f.pin<h.duration+h.delay)for(h=h.duration+h.delay-f.pin,f.pin+=h,c=g+1;c<k.length;c++)k[c].top+=h,k[c].block.css("top",k[c].top)}e()};g.onBlockChange=function(a){q=a};g.getScrollpoints=function(){var a=[],b,c;for(b=0;b<k.length;b++)if(a.push(k[b].top),k[b].animations.length&&0<k[b].pin)for(c=0;c<k[b].animations.length;c++){var e=k[b].animations[c];a.push(k[b].top+
e.delay+e.duration)}a.sort(function(a,b){return a-b});return a};(function(){var b;"string"===typeof g.settings.blocks&&(g.settings.blocks=d(g.settings.blocks));d.browser.mozilla&&(m="-moz-");d.browser.webkit&&(m="-webkit-");d.browser.opera&&(m="-o-");d.browser.msie&&(m="-ms-");d("body").css("position","relative");for(b=0;b<g.settings.blocks.length;b++){var c=g.settings.blocks.eq(b);k.push({block:c,top:c.offset().top-parseInt(c.css("margin-top"),10),pin:0,animations:[]})}if("true"===g.settings.enablePin.toString())for(b=
0;b<k.length;b++)k[b].block.css("position","absolute").css("top",k[b].top);d("body").prepend('<div id="scroll-wrap"></div>');r=!1;d(window).scroll(a)})();return g};d.extend(d.easing,{def:"easeOutQuad",swing:function(b,a,c,e,f){return d.easing[d.easing.def](b,a,c,e,f)},easeInQuad:function(b,a,c,e,d){return e*(a/=d)*a+c},easeOutQuad:function(b,a,c,e,d){return-e*(a/=d)*(a-2)+c},easeInOutQuad:function(b,a,c,e,d){return 1>(a/=d/2)?e/2*a*a+c:-e/2*(--a*(a-2)-1)+c},easeInCubic:function(b,a,c,e,d){return e*
(a/=d)*a*a+c},easeOutCubic:function(b,a,c,e,d){return e*((a=a/d-1)*a*a+1)+c},easeInOutCubic:function(b,a,c,e,d){return 1>(a/=d/2)?e/2*a*a*a+c:e/2*((a-=2)*a*a+2)+c},easeInQuart:function(b,a,c,e,d){return e*(a/=d)*a*a*a+c},easeOutQuart:function(b,a,c,e,d){return-e*((a=a/d-1)*a*a*a-1)+c},easeInOutQuart:function(b,a,c,e,d){return 1>(a/=d/2)?e/2*a*a*a*a+c:-e/2*((a-=2)*a*a*a-2)+c},easeInQuint:function(b,a,c,e,d){return e*(a/=d)*a*a*a*a+c},easeOutQuint:function(b,a,c,e,d){return e*((a=a/d-1)*a*a*a*a+1)+
c},easeInOutQuint:function(b,a,c,e,d){return 1>(a/=d/2)?e/2*a*a*a*a*a+c:e/2*((a-=2)*a*a*a*a+2)+c},easeInSine:function(b,a,c,e,d){return-e*Math.cos(a/d*(Math.PI/2))+e+c},easeOutSine:function(b,a,c,e,d){return e*Math.sin(a/d*(Math.PI/2))+c},easeInOutSine:function(b,a,c,e,d){return-e/2*(Math.cos(Math.PI*a/d)-1)+c},easeInExpo:function(b,a,c,e,d){return 0===a?c:e*Math.pow(2,10*(a/d-1))+c},easeOutExpo:function(b,a,c,e,d){return a===d?c+e:e*(-Math.pow(2,-10*a/d)+1)+c},easeInOutExpo:function(b,a,c,e,d){return 0===
a?c:a===d?c+e:1>(a/=d/2)?e/2*Math.pow(2,10*(a-1))+c:e/2*(-Math.pow(2,-10*--a)+2)+c},easeInCirc:function(b,a,c,e,d){return-e*(Math.sqrt(1-(a/=d)*a)-1)+c},easeOutCirc:function(b,a,c,e,d){return e*Math.sqrt(1-(a=a/d-1)*a)+c},easeInOutCirc:function(b,a,c,e,d){return 1>(a/=d/2)?-e/2*(Math.sqrt(1-a*a)-1)+c:e/2*(Math.sqrt(1-(a-=2)*a)+1)+c},easeInElastic:function(b,a,c,e,d){b=0;var f=e;if(0===a)return c;if(1===(a/=d))return c+e;b||(b=.3*d);f<Math.abs(e)?(f=e,e=b/4):e=b/(2*Math.PI)*Math.asin(e/f);return-(f*
Math.pow(2,10*--a)*Math.sin(2*(a*d-e)*Math.PI/b))+c},easeOutElastic:function(b,a,c,d,f){var e=0,k=d;if(0===a)return c;if(1===(a/=f))return c+d;e||(e=.3*f);k<Math.abs(d)?(k=d,b=e/4):b=e/(2*Math.PI)*Math.asin(d/k);return k*Math.pow(2,-10*a)*Math.sin(2*(a*f-b)*Math.PI/e)+d+c},easeInOutElastic:function(b,a,c,d,f){var e=0,k=d;if(0===a)return c;if(2===(a/=f/2))return c+d;e||(e=.3*f*1.5);k<Math.abs(d)?(k=d,b=e/4):b=e/(2*Math.PI)*Math.asin(d/k);return 1>a?-.5*k*Math.pow(2,10*--a)*Math.sin(2*(a*f-b)*Math.PI/
e)+c:k*Math.pow(2,-10*--a)*Math.sin(2*(a*f-b)*Math.PI/e)*.5+d+c},easeInBack:function(b,a,c,d,f,g){void 0===g&&(g=1.70158);return d*(a/=f)*a*((g+1)*a-g)+c},easeOutBack:function(b,a,c,d,f,g){void 0===g&&(g=1.70158);return d*((a=a/f-1)*a*((g+1)*a+g)+1)+c},easeInOutBack:function(b,a,c,d,f,g){void 0===g&&(g=1.70158);return 1>(a/=f/2)?d/2*a*a*(((g*=1.525)+1)*a-g)+c:d/2*((a-=2)*a*(((g*=1.525)+1)*a+g)+2)+c},easeInBounce:function(b,a,c,e,f){return e-d.easing.easeOutBounce(b,f-a,0,e,f)+c},easeOutBounce:function(b,
a,c,d,f){return(a/=f)<1/2.75?7.5625*d*a*a+c:a<2/2.75?d*(7.5625*(a-=1.5/2.75)*a+.75)+c:a<2.5/2.75?d*(7.5625*(a-=2.25/2.75)*a+.9375)+c:d*(7.5625*(a-=2.625/2.75)*a+.984375)+c},easeInOutBounce:function(b,a,c,e,f){return a<f/2?.5*d.easing.easeInBounce(b,2*a,0,e,f)+c:.5*d.easing.easeOutBounce(b,2*a-f,0,e,f)+.5*e+c}})})(jQuery);jQuery.easing.jswing=jQuery.easing.swing;
jQuery.extend(jQuery.easing,{def:"easeOutQuad",swing:function(d,b,a,c,e){return jQuery.easing[jQuery.easing.def](d,b,a,c,e)},easeInQuad:function(d,b,a,c,e){return c*(b/=e)*b+a},easeOutQuad:function(d,b,a,c,e){return-c*(b/=e)*(b-2)+a},easeInOutQuad:function(d,b,a,c,e){return 1>(b/=e/2)?c/2*b*b+a:-c/2*(--b*(b-2)-1)+a},easeInCubic:function(d,b,a,c,e){return c*(b/=e)*b*b+a},easeOutCubic:function(d,b,a,c,e){return c*((b=b/e-1)*b*b+1)+a},easeInOutCubic:function(d,b,a,c,e){return 1>(b/=e/2)?c/2*b*b*b+a:
c/2*((b-=2)*b*b+2)+a},easeInQuart:function(d,b,a,c,e){return c*(b/=e)*b*b*b+a},easeOutQuart:function(d,b,a,c,e){return-c*((b=b/e-1)*b*b*b-1)+a},easeInOutQuart:function(d,b,a,c,e){return 1>(b/=e/2)?c/2*b*b*b*b+a:-c/2*((b-=2)*b*b*b-2)+a},easeInQuint:function(d,b,a,c,e){return c*(b/=e)*b*b*b*b+a},easeOutQuint:function(d,b,a,c,e){return c*((b=b/e-1)*b*b*b*b+1)+a},easeInOutQuint:function(d,b,a,c,e){return 1>(b/=e/2)?c/2*b*b*b*b*b+a:c/2*((b-=2)*b*b*b*b+2)+a},easeInSine:function(d,b,a,c,e){return-c*Math.cos(b/
e*(Math.PI/2))+c+a},easeOutSine:function(d,b,a,c,e){return c*Math.sin(b/e*(Math.PI/2))+a},easeInOutSine:function(d,b,a,c,e){return-c/2*(Math.cos(Math.PI*b/e)-1)+a},easeInExpo:function(d,b,a,c,e){return 0==b?a:c*Math.pow(2,10*(b/e-1))+a},easeOutExpo:function(d,b,a,c,e){return b==e?a+c:c*(-Math.pow(2,-10*b/e)+1)+a},easeInOutExpo:function(d,b,a,c,e){return 0==b?a:b==e?a+c:1>(b/=e/2)?c/2*Math.pow(2,10*(b-1))+a:c/2*(-Math.pow(2,-10*--b)+2)+a},easeInCirc:function(d,b,a,c,e){return-c*(Math.sqrt(1-(b/=e)*
b)-1)+a},easeOutCirc:function(d,b,a,c,e){return c*Math.sqrt(1-(b=b/e-1)*b)+a},easeInOutCirc:function(d,b,a,c,e){return 1>(b/=e/2)?-c/2*(Math.sqrt(1-b*b)-1)+a:c/2*(Math.sqrt(1-(b-=2)*b)+1)+a},easeInElastic:function(d,b,a,c,e){d=0;var f=c;if(0==b)return a;if(1==(b/=e))return a+c;d||(d=.3*e);f<Math.abs(c)?(f=c,c=d/4):c=d/(2*Math.PI)*Math.asin(c/f);return-(f*Math.pow(2,10*--b)*Math.sin(2*(b*e-c)*Math.PI/d))+a},easeOutElastic:function(d,b,a,c,e){var f=0,g=c;if(0==b)return a;if(1==(b/=e))return a+c;f||
(f=.3*e);g<Math.abs(c)?(g=c,d=f/4):d=f/(2*Math.PI)*Math.asin(c/g);return g*Math.pow(2,-10*b)*Math.sin(2*(b*e-d)*Math.PI/f)+c+a},easeInOutElastic:function(d,b,a,c,e){var f=0,g=c;if(0==b)return a;if(2==(b/=e/2))return a+c;f||(f=.3*e*1.5);g<Math.abs(c)?(g=c,d=f/4):d=f/(2*Math.PI)*Math.asin(c/g);return 1>b?-.5*g*Math.pow(2,10*--b)*Math.sin(2*(b*e-d)*Math.PI/f)+a:g*Math.pow(2,-10*--b)*Math.sin(2*(b*e-d)*Math.PI/f)*.5+c+a},easeInBack:function(d,b,a,c,e,f){void 0==f&&(f=1.70158);return c*(b/=e)*b*((f+1)*
b-f)+a},easeOutBack:function(d,b,a,c,e,f){void 0==f&&(f=1.70158);return c*((b=b/e-1)*b*((f+1)*b+f)+1)+a},easeInOutBack:function(d,b,a,c,e,f){void 0==f&&(f=1.70158);return 1>(b/=e/2)?c/2*b*b*(((f*=1.525)+1)*b-f)+a:c/2*((b-=2)*b*(((f*=1.525)+1)*b+f)+2)+a},easeInBounce:function(d,b,a,c,e){return c-jQuery.easing.easeOutBounce(d,e-b,0,c,e)+a},easeOutBounce:function(d,b,a,c,e){return(b/=e)<1/2.75?7.5625*c*b*b+a:b<2/2.75?c*(7.5625*(b-=1.5/2.75)*b+.75)+a:b<2.5/2.75?c*(7.5625*(b-=2.25/2.75)*b+.9375)+a:c*(7.5625*
(b-=2.625/2.75)*b+.984375)+a},easeInOutBounce:function(d,b,a,c,e){return b<e/2?.5*jQuery.easing.easeInBounce(d,2*b,0,c,e)+a:.5*jQuery.easing.easeOutBounce(d,2*b-e,0,c,e)+.5*c+a}});jQuery.noConflict();
function bgCarousel(d){var b=jQuery;this.setting={displaymode:{type:"auto",pause:2E3,stoponclick:!1,cycles:2,pauseonmouseover:!0},activeslideclass:"selectedslide",orientation:"h",persist:!0,slideduration:500};jQuery.extend(this.setting,d);this.setting.displaymode.pause+=400+this.setting.slideduration;d=this.setting.persist?bgCarousel.routines.getCookie("slider-"+this.setting.wrapperid):0;this.curslide=null==d||d>this.setting.imagearray.length-1?0:parseInt(d);this.curstep=0;this.animation_isrunning=
!1;this.posprop="h"==this.setting.orientation?"left":"top";d=null;var a=this,c=this.setting;d=[];for(var e=0,f="",g=0,k=c.imagearray.length;g<k;g++)d[g]=new Image,b(d[g]).bind("load error",function(){e++;e==k&&b(function(){a.init(b,f)})}),d[g].src=c.imagearray[g][0],f+=bgCarousel.routines.getSlideHTML(c,c.imagearray[g],"100%","100%",this.posprop)+"\n";b(window).bind("unload",function(){a.setting.persist&&bgCarousel.routines.setCookie("slider-"+c.wrapperid,a.curslide)})}
bgCarousel.prototype={slide:function(d,b){if(this.curslide!=d){var a=this,c=this.setting,e=bgCarousel.routines.createobj;b=c.dimensions["right"==b||"left"==b?0:1]*("right"==b||"down"==b?-1:1);var f=-b,g=this.posprop;null!=this.animation_isrunning&&(this.animation_isrunning=!0);this.$imageslides.eq(d).show().css(e([g,b],["opacity",.5])).stop().animate(e([g,0]),c.slideduration,function(){jQuery(this).addClass(c.activeslideclass).animate({opacity:1}).find("div.desc").stop().slideDown();a.animation_isrunning=
!1}).find("div.desc").hide();this.$imageslides.eq(this.curslide).removeClass(c.activeslideclass).stop().animate(e([g,f]),c.slideduration,function(){jQuery(this).hide()});this.curslide=d}},navigate:function(d){var b=this,a=this.setting;clearTimeout(this.rotatetimer);a.displaymode.stoponclick||"manual"==a.displaymode.type||(this.curstep="back"==d?this.curstep-1:this.curstep+1,this.rotatetimer=setTimeout(function(){b.rotate()},a.displaymode.pause));a="back"==d?"h"==a.orientation?"right":"down":"h"==
a.orientation?"left":"up";d="back"==d?this.curslide-1:this.curslide+1;d=0>d?this.$imageslides.length-1:d>this.$imageslides.length-1?0:d;0==this.animation_isrunning&&this.slide(d,a)},rotate:function(){var d=this,b=this.setting;if(this.ismouseover)this.rotatetimer=setTimeout(function(){d.rotate()},b.displaymode.pause);else if(this.slide(this.curslide<this.$imageslides.length-1?this.curslide+1:0,this.posprop),0==b.displaymode.cycles||this.curstep<this.maxsteps-1)this.rotatetimer=setTimeout(function(){d.rotate()},
b.displaymode.pause),this.curstep++},init:function(d,b){var a=this,c=this.setting;this.$wrapperdiv=d("#"+c.wrapperid);c.dimensions=[this.$wrapperdiv.width(),this.$wrapperdiv.height()];this.$wrapperdiv.css({position:"relative",visibility:"visible",overflow:"hidden",backgroundImage:"none",width:c.dimensions[0],height:c.dimensions[1]});0==this.$wrapperdiv.length?alert('Error: DIV with ID "'+c.wrapperid+'" not found on page.'):(this.$wrapperdiv.html(b),this.$imageslides=this.$wrapperdiv.find("div.background").hide(),
this.$imageslides.eq(this.curslide).show().css(bgCarousel.routines.createobj(["opacity",.5],[this.posprop,0])).addClass(c.activeslideclass).stop().animate({opacity:1}).find("div.desc").slideDown(),"h"==c.orientation?c.navbuttons.slice(0,2):c.navbuttons.slice(2),d("").click(function(){var b=this.getAttribute("data-dir");c.curslide="right"==b?c.curslide==c.content.length-1?0:c.curslide+1:0==c.curslide?c.content.length-1:c.curslide-1;a.navigate(b)}).appendTo(this.$wrapperdiv),"auto"==c.displaymode.type&&
(c.displaymode.pause+=c.slideduration,this.maxsteps=c.displaymode.cycles*this.$imageslides.length,c.displaymode.pauseonmouseover&&(this.$wrapperdiv.mouseenter(function(){a.ismouseover=!0}),this.$wrapperdiv.mouseleave(function(){a.ismouseover=!1})),this.rotatetimer=setTimeout(function(){a.rotate()},c.displaymode.pause)))}};
bgCarousel.routines={getSlideHTML:function(d,b,a,c,e){return'<div class="background" style="background-image:url('+b[0]+");"+(e+":"+("left"==e?a:c))+'">'+(b[1]?'<div class="desc" style="display:none">'+b[1]+"</div>\n":"")+"</div>"},getCookie:function(d){d=new RegExp(d+"=[^;]+","i");return document.cookie.match(d)?document.cookie.match(d)[0].split("=")[1]:null},setCookie:function(d,b){document.cookie=d+"="+b+";path=/"},createobj:function(){for(var d={},b=0;b<arguments.length;b++)d[arguments[b][0]]=
arguments[b][1];return d}}; //# sourceMappingURL=/en/t4-media/one-web/university/admin-assets/js/map/plugins-min.js.map
