/*
 FitVids 1.1

 Copyright 2013, Chris Coyier - http://css-tricks.com + Dave Rupert - http://daverupert.com
 Credit to Thierry Koblentz - http://www.alistapart.com/articles/creating-intrinsic-ratios-for-video/
 Released under the WTFPL license - http://sam.zoy.org/wtfpl/

*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,e,c){a instanceof String&&(a=String(a));for(var f=a.length,d=0;d<f;d++){var g=a[d];if(e.call(c,g,d,a))return{i:d,v:g}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,c){a!=Array.prototype&&a!=Object.prototype&&(a[e]=c.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,e,c,f){if(e){c=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var d=a[f];d in c||(c[d]={});c=c[d]}a=a[a.length-1];f=c[a];e=e(f);e!=f&&null!=e&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:e})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");
(function(a){a.fn.fitVids=function(e){var c={customSelector:null,ignore:null};if(!document.getElementById("fit-vids-style")){var f=document.head||document.getElementsByTagName("head")[0],d=document.createElement("div");d.innerHTML='<p>x</p><style id="fit-vids-style">.fluid-width-video-wrapper{width:100%;position:relative;padding:0;}.fluid-width-video-wrapper iframe,.fluid-width-video-wrapper object,.fluid-width-video-wrapper embed {position:absolute;top:0;left:0;width:100%;height:100%;}</style>';f.appendChild(d.childNodes[1])}e&&
a.extend(c,e);return this.each(function(){var d='iframe[src*="player.vimeo.com"] iframe[src*="youtube.com"] iframe[src*="youtube-nocookie.com"] iframe[src*="kickstarter.com"][src*="video.html"] object embed'.split(" ");c.customSelector&&d.push(c.customSelector);var e=".fitvidsignore";c.ignore&&(e=e+", "+c.ignore);d=a(this).find(d.join(","));d=d.not("object object");d=d.not(e);d.each(function(){var b=a(this);if(!(0<b.parents(e).length||"embed"===this.tagName.toLowerCase()&&b.parent("object").length||
b.parent(".fluid-width-video-wrapper").length)){b.css("height")||b.css("width")||!isNaN(b.attr("height"))&&!isNaN(b.attr("width"))||(b.attr("height",9),b.attr("width",16));var d="object"===this.tagName.toLowerCase()||b.attr("height")&&!isNaN(parseInt(b.attr("height"),10))?parseInt(b.attr("height"),10):b.height(),c=isNaN(parseInt(b.attr("width"),10))?b.width():parseInt(b.attr("width"),10);d/=c;.5==d&&(d=.5625);b.attr("name")||(b.attr("name","fitvid"+a.fn.fitVids._count),a.fn.fitVids._count++);b.wrap('<div class="fluid-width-video-wrapper"></div>').parent(".fluid-width-video-wrapper").css("padding-top",
100*d+"%");b.removeAttr("height").removeAttr("width")}})})};a.fn.fitVids._count=0})(window.jQuery||window.Zepto);/*
 A simple jQuery modal (http://github.com/kylefox/jquery-modal)
    Version 0.9.2
*/
(function(a){"object"===typeof module&&"object"===typeof module.exports?a(require("jquery"),window,document):a(jQuery,window,document)})(function(a,e,c,f){var d=[],g=function(){return d.length?d[d.length-1]:null},h=function(){var a,c=!1;for(a=d.length-1;0<=a;a--)d[a].$blocker&&(d[a].$blocker.toggleClass("current",!c).toggleClass("behind",c),c=!0)};a.modal=function(b,c){this.$body=a("body");this.options=a.extend({},a.modal.defaults,c);this.options.doFade=!isNaN(parseInt(this.options.fadeDuration,10));
this.$blocker=null;if(this.options.closeExisting)for(;a.modal.isActive();)a.modal.close();d.push(this);if(b.is("a"))if(c=b.attr("href"),this.anchor=b,/^#/.test(c)){this.$elm=a(c);if(1!==this.$elm.length)return null;this.$body.append(this.$elm);this.open()}else{this.$elm=a("<div>");this.$body.append(this.$elm);var e=function(a,b){b.elm.remove()};this.showSpinner();b.trigger(a.modal.AJAX_SEND);a.get(c).done(function(d){if(a.modal.isActive()){b.trigger(a.modal.AJAX_SUCCESS);var c=g();c.$elm.empty().append(d).on(a.modal.CLOSE,
e);c.hideSpinner();c.open();b.trigger(a.modal.AJAX_COMPLETE)}}).fail(function(){b.trigger(a.modal.AJAX_FAIL);g().hideSpinner();d.pop();b.trigger(a.modal.AJAX_COMPLETE)})}else this.anchor=this.$elm=b,this.$body.append(this.$elm),this.open()};a.modal.prototype={constructor:a.modal,open:function(){var b=this;this.block();this.anchor.blur();this.options.doFade?setTimeout(function(){b.show()},this.options.fadeDuration*this.options.fadeDelay):this.show();a(c).off("keydown.modal").on("keydown.modal",function(a){var b=
g();27===a.which&&b.options.escapeClose&&b.close()});this.options.clickClose&&this.$blocker.click(function(b){b.target===this&&a.modal.close()})},close:function(){d.pop();this.unblock();this.hide();a.modal.isActive()||a(c).off("keydown.modal")},block:function(){this.$elm.trigger(a.modal.BEFORE_BLOCK,[this._ctx()]);this.$body.css("overflow","hidden");this.$blocker=a('<div class="'+this.options.blockerClass+' blocker current"></div>').appendTo(this.$body);h();this.options.doFade&&this.$blocker.css("opacity",
0).animate({opacity:1},this.options.fadeDuration);this.$elm.trigger(a.modal.BLOCK,[this._ctx()])},unblock:function(b){!b&&this.options.doFade?this.$blocker.fadeOut(this.options.fadeDuration,this.unblock.bind(this,!0)):(this.$blocker.children().appendTo(this.$body),this.$blocker.remove(),this.$blocker=null,h(),a.modal.isActive()||this.$body.css("overflow",""))},show:function(){this.$elm.trigger(a.modal.BEFORE_OPEN,[this._ctx()]);this.options.showClose&&(this.closeButton=a('<a href="#close-modal" rel="modal:close" class="close-modal '+
this.options.closeClass+'">'+this.options.closeText+"</a>"),this.$elm.append(this.closeButton));this.$elm.addClass(this.options.modalClass).appendTo(this.$blocker);this.options.doFade?this.$elm.css({opacity:0,display:"inline-block"}).animate({opacity:1},this.options.fadeDuration):this.$elm.css("display","inline-block");this.$elm.trigger(a.modal.OPEN,[this._ctx()])},hide:function(){this.$elm.trigger(a.modal.BEFORE_CLOSE,[this._ctx()]);this.closeButton&&this.closeButton.remove();var b=this;this.options.doFade?
this.$elm.fadeOut(this.options.fadeDuration,function(){b.$elm.trigger(a.modal.AFTER_CLOSE,[b._ctx()])}):this.$elm.hide(0,function(){b.$elm.trigger(a.modal.AFTER_CLOSE,[b._ctx()])});this.$elm.trigger(a.modal.CLOSE,[this._ctx()])},showSpinner:function(){this.options.showSpinner&&(this.spinner=this.spinner||a('<div class="'+this.options.modalClass+'-spinner"></div>').append(this.options.spinnerHtml),this.$body.append(this.spinner),this.spinner.show())},hideSpinner:function(){this.spinner&&this.spinner.remove()},
_ctx:function(){return{elm:this.$elm,$elm:this.$elm,$blocker:this.$blocker,options:this.options,$anchor:this.anchor}}};a.modal.close=function(b){if(a.modal.isActive())return b&&b.preventDefault(),b=g(),b.close(),b.$elm};a.modal.isActive=function(){return 0<d.length};a.modal.getCurrent=g;a.modal.defaults={closeExisting:!0,escapeClose:!0,clickClose:!0,closeText:"Close",closeClass:"",modalClass:"modal",blockerClass:"jquery-modal",spinnerHtml:'<div class="rect1"></div><div class="rect2"></div><div class="rect3"></div><div class="rect4"></div>',
showSpinner:!0,showClose:!0,fadeDuration:null,fadeDelay:1};a.modal.BEFORE_BLOCK="modal:before-block";a.modal.BLOCK="modal:block";a.modal.BEFORE_OPEN="modal:before-open";a.modal.OPEN="modal:open";a.modal.BEFORE_CLOSE="modal:before-close";a.modal.CLOSE="modal:close";a.modal.AFTER_CLOSE="modal:after-close";a.modal.AJAX_SEND="modal:ajax:send";a.modal.AJAX_SUCCESS="modal:ajax:success";a.modal.AJAX_FAIL="modal:ajax:fail";a.modal.AJAX_COMPLETE="modal:ajax:complete";a.fn.modal=function(b){1===this.length&&
new a.modal(this,b);return this};a(c).on("click.modal",'a[rel~="modal:close"]',a.modal.close);a(c).on("click.modal",'a[rel~="modal:open"]',function(b){b.preventDefault();a(this).modal()})}); //# sourceMappingURL=/en/t4-media/one-web/university/admin-assets/js/map/plugins-min.js.map
