/*
 User editable tabs for WYSIWYG HTML editors using jQueryuery Tools.

 Idea and code taken from Mikko Ohtamaa's wysiwygTabs with permission.

 @author Michael Dunlap <dunlapm@uw.edu>

 @copyright University of Washington

 @license GPL

 @version 1.0

*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,d,c){a instanceof String&&(a=String(a));for(var e=a.length,b=0;b<e;b++){var f=a[b];if(d.call(c,f,b,a))return{i:b,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,c){a!=Array.prototype&&a!=Object.prototype&&(a[d]=c.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,d,c,e){if(d){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var b=a[e];b in c||(c[b]={});c=c[b]}a=a[a.length-1];e=c[a];d=d(e);d!=e&&null!=d&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:d})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");wysiwygTabs={PANE_CLASS:"pane",PANE_CONTAINER_CLASS:"pane-container",TAB_CONTAINER_CLASS:"tabs",TAB_MARKER:"content-tab",DEFAULT_TAB_MARKER:"default-content-tab",PANE_END_CLASS:"pane-break"};wysiwygTabs.PANE_END_MARKER="hr."+wysiwygTabs.PANE_END_CLASS;wysiwygTabs.DEBUG=!1;wysiwygTabs.idCounter=0;wysiwygTabs.containerCounter=0;wysiwygTabs.defaults=[];
wysiwygTabs.Tab=function(a,d){this.id=null;this.classes=d;this.title=a;this.content=jQuery('<div class="'+wysiwygTabs.PANE_CLASS+'">\x3c!-- Dynamically generated pane --\x3e</div>')};
wysiwygTabs.collectTabs=function(){wysiwygTabs.DEBUG&&wysiwygTabs.log("Creating tabs");jQuery("h2."+wysiwygTabs.TAB_MARKER+", h2."+wysiwygTabs.DEFAULT_TAB_MARKER).parent().each(function(){var a=[];wysiwygTabs.containerCounter++;wysiwygTabs.defaults[wysiwygTabs.containerCounter]=0;var d=null,c=null,e=this;wysiwygTabs.DEBUG&&wysiwygTabs.log("Scanning field "+jQuery(e).attr("id"));jQuery(e).contents().each(function(b,f){b=jQuery(this);wysiwygTabs.DEBUG&&wysiwygTabs.log("Walking "+f);b.is(wysiwygTabs.PANE_END_MARKER)?
(wysiwygTabs.DEBUG&&wysiwygTabs.log("hit end marker "+b.attr("id")),c=wysiwygTabs.constructContainer(a),b.replaceWith(c),a=[],d=null):b.hasClass(wysiwygTabs.TAB_MARKER)||b.hasClass(wysiwygTabs.DEFAULT_TAB_MARKER)?(b.hasClass(wysiwygTabs.DEFAULT_TAB_MARKER)&&(wysiwygTabs.defaults[wysiwygTabs.containerCounter]=a.length),wysiwygTabs.DEBUG&&wysiwygTabs.log("Making tab: "+b.text()),b.removeClass(wysiwygTabs.TAB_MARKER),b.removeClass(wysiwygTabs.DEFAULT_TAB_MARKER),f=new wysiwygTabs.Tab(b.text(),b.attr("class")),
wysiwygTabs.DEBUG&&b.attr("class")&&wysiwygTabs.log("found classes: "+b.attr("class")),a.push(f),d=f,e.removeChild(this)):null!=d&&(e.removeChild(this),d.content.append(this))});wysiwygTabs.DEBUG&&wysiwygTabs.log("constructing container with "+a.length+" tabs");c=wysiwygTabs.constructContainer(a);jQuery(e).append(c)});wysiwygTabs.DEBUG&&wysiwygTabs.log("Found tab count:"+wysiwygTabs.idCounter)};
wysiwygTabs.constructContainer=function(a){wysiwygTabs.DEBUG&&wysiwygTabs.log("Constructing tab container for tabs "+a.length);idcnt=wysiwygTabs.containerCounter++;var d=jQuery('<div class="'+wysiwygTabs.PANE_CONTAINER_CLASS+'" id="container-'+idcnt+'">\x3c!-- Dynamically generated tab  container --\x3e</div>'),c=jQuery('<ul class="'+wysiwygTabs.TAB_CONTAINER_CLASS+'">\x3c!-- Dynamically generated tab selectors --\x3e</ul>'),e;if(0==a.length)return null;for(e=0;e<a.length;e++){var b=a[e];wysiwygTabs.DEBUG&&
wysiwygTabs.log("Creating tab selector "+b.title);b.id=wysiwygTabs.idCounter++;var f=jQuery("<li></li>");f.attr({"class":"wysiwygTab-selector",id:"wysiwygTab-selector-"+b.id});var g=jQuery("<a></a>");g.attr({id:"wysiwygTab-link-"+b.id,href:"#wysiwygTab-content-"+b.id,"class":b.classes});g.append(b.title);f.append(g);c.append(f)}d.append(c);for(e=0;e<a.length;e++)b=a[e],c=b.content,c.attr({id:"wysiwygTab-content-"+b.id}),d.append(c),d.prepend(c.find("a[name^='section-']"));return d};
wysiwygTabs.init=function(){jQuery(function(){jQuery(".kupu-fulleditor #toolbar").each(function(){jQuery(this).find("#kupu-bg-indent").after('<span id="#kupu-hr-buttongroup"class="kupu-tb-buttongroup"><button title="Insert pane break" class="kupu-inserthorizontalrule" type="button";>&nbsp;</button></span>')});jQuery(".kupu-inserthorizontalrule").click(function(){var a=window.kupu,d=a.getSelectedNode();a=a.newElement("hr");a.setAttribute("class",wysiwygTabs.PANE_END_CLASS);d.appendChild(a)})});"on"!=
document.designMode.toLowerCase()&&(wysiwygTabs.collectTabs(),jQuery(".pane-container").tabs(),tocLinks=jQuery("#document-toc a"),tabLinks=jQuery("#content ul.tabs a"),tocLinks.click(function(){link=jQuery(this);tabLinks.each(function(){tab=jQuery(this);if(tab.text()==link.text())return tab.click(),!1})}))};wysiwygTabs.log=function(a){"undefined"!=typeof console&&"undefined"!=typeof console.log&&console.log(a)};jQuery(wysiwygTabs.init); //# sourceMappingURL=/en/t4-media/one-web/university/admin-assets/js/map/tabr-min.js.map
